// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
     show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1v3MPO0tn8SKSUc2ctuBYnh_A_frM7Js',
    appId: '1:5433093493:web:83ed2f81a1996ba834373c',
    messagingSenderId: '5433093493',
    projectId: 'ojourbano',
    authDomain: 'ojourbano.firebaseapp.com',
    storageBucket: 'ojourbano.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEfJbgWQzFNt6SkQCGPrwYF1GVVq2qLn4',
    appId: '1:5433093493:android:0ce1cf7c8ae7715834373c',
    messagingSenderId: '5433093493',
    projectId: 'ojourbano',
    storageBucket: 'ojourbano.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOH43hrXPfxnpSNdRag2ytmu1J4yUxTe8',
    appId: '1:5433093493:ios:0aae4f80cfcb0f9134373c',
    messagingSenderId: '5433093493',
    projectId: 'ojourbano',
    storageBucket: 'ojourbano.firebasestorage.app',
    iosBundleId: 'com.example.ojoUrbano',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOH43hrXPfxnpSNdRag2ytmu1J4yUxTe8',
    appId: '1:5433093493:ios:0aae4f80cfcb0f9134373c',
    messagingSenderId: '5433093493',
    projectId: 'ojourbano',
    storageBucket: 'ojourbano.firebasestorage.app',
    iosBundleId: 'com.example.ojoUrbano',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1v3MPO0tn8SKSUc2ctuBYnh_A_frM7Js',
    appId: '1:5433093493:web:e676fd9a28db7d1134373c',
    messagingSenderId: '5433093493',
    projectId: 'ojourbano',
    authDomain: 'ojourbano.firebaseapp.com',
    storageBucket: 'ojourbano.firebasestorage.app',
  );
}
